### ISSUE TITLE
Request for Code Licensing or Permission

### ISSUE THREAD

**Issue by xsa-dev** [nicoDs96/Trading-Bot---Deep-Reinforcement-Learning#1]
Hello Nicola Di Santo,

I hope this message finds you well. I've been following your project on GitHub, and I'm really impressed with the work you've done. Your code could be valuable for my own project, but I noticed that it's currently not licensed.

I wanted to kindly request if you could consider adding an open-source license to your repository. This would clarify how others, including me, can use and contribute to your code while respecting your intentions.

Alternatively, if you prefer to grant individual permissions for usage, please let me know what terms you'd be comfortable with. I'm eager to discuss this further and ensure proper attribution and compliance with your wishes.

Thank you for your time and consideration. I look forward to your response.

Best regards,
Aleksey Savin

**Comment by xsa-dev** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by nicoDs96** [comment]
Hi, thank you for the advice. I have added a license, for me you can do whatever you want, just remeber me if you ever became rich thanks to this code 😆
