### ISSUE TITLE
CLI mode

### ISSUE THREAD

**Issue by xsa-dev** [nicoDs96/Trading-Bot---Deep-Reinforcement-Learning#3]
To facilitate simpler user interactions, we propose incorporating a "cli mode" feature into our application. This feature would allow users to access a command-line interface (CLI) within the app, enabling them to execute various tasks with ease and efficiency. By providing this functionality, we can streamline the user experience and make it more intuitive for those who prefer working through a CLI.

**Comment by nicoDs96** [comment]
Hi @xsa-dev, maybe you wanted to open the issue on your fork otherwise I don't understand what are you talking about. If is not the case can you detail a little bit more? 
Thank you

**Comment by xsa-dev** [comment]
I am sorry. Yes.
